export const ONBOARDING_FLOWS = {
  fleet: {
    id: "fleet",
    title: "Add Your First Aircraft",
    description: "Register an aircraft to enable flight tracking and FRAT submissions",
    tab: "admin",
    adminTab: "fleet",
    steps: [
      {
        id: "enter_type",
        target: "[data-onboarding='fleet-type-input']",
        title: "Aircraft Type",
        description: "Enter your aircraft type — for example, C172 or R44.",
        advanceOn: "continue",
      },
      {
        id: "enter_reg",
        target: "[data-onboarding='fleet-reg-input']",
        title: "Tail Number",
        description: "Enter the registration / tail number. We'll auto-add the N prefix.",
        advanceOn: "continue",
      },
      {
        id: "complete_form",
        target: "[data-onboarding='fleet-form']",
        title: "Complete the Details",
        description: "Fill in any remaining fields, then click Add Aircraft to save.",
        advanceOn: "save",
      },
      {
        id: "congrats",
        target: null,
        title: "Aircraft Added!",
        description: "Your fleet is started. You're ready to track flights and submit risk assessments.",
        advanceOn: "dismiss",
      },
    ],
  },
  frat: {
    id: "frat",
    title: "Submit Your First FRAT",
    description: "Walk through a Flight Risk Assessment to learn how risk scoring works",
    tab: "submit",
    steps: [
      { id: "frat_pilot", target: "[data-onboarding='frat-pilot']", title: "Pilot in Command", description: "Enter the pilot's name for this flight.", advanceOn: "continue" },
      { id: "frat_aircraft", target: "[data-onboarding='frat-aircraft']", title: "Aircraft", description: "Select the aircraft type from your fleet.", advanceOn: "continue" },
      { id: "frat_departure", target: "[data-onboarding='frat-departure']", title: "Departure Airport", description: "Enter the ICAO code for your departure airport (e.g. KSFF).", advanceOn: "continue" },
      { id: "frat_destination", target: "[data-onboarding='frat-destination']", title: "Destination Airport", description: "Enter the ICAO code for your destination (e.g. KBOI).", advanceOn: "continue" },
      { id: "frat_remaining", target: "[data-onboarding='frat-flight-info']", title: "Complete Flight Details", description: "Fill in the remaining fields — altitude, date, times, fuel, crew, and passengers.", advanceOn: "continue" },
      { id: "frat_photos", target: "[data-onboarding='frat-photos']", title: "Attachments", description: "Attach photos of HAZMAT PIC notifications or other documents. This step is optional — click Continue to proceed.", advanceOn: "continue" },
      { id: "frat_wx_brief", target: "[data-onboarding='frat-weather-briefing']", title: "Weather Briefing", description: "Review the weather briefing for your departure and destination airports. METARs, TAFs, and flight rules are displayed automatically.", advanceOn: "continue" },
      { id: "frat_ai", target: "[data-onboarding='frat-ai-panel']", title: "AI Risk Suggestions", description: "Try AI-powered risk analysis. AI suggests risk categories based on historical FRATs, your planned flight, current weather, and terrain data.", advanceOn: "continue" },
      { id: "frat_wx", target: "[data-onboarding='frat-cat-weather']", title: "Weather Factors", description: "Review and select any weather hazards that apply to this flight.", advanceOn: "continue" },
      { id: "frat_pilot_cat", target: "[data-onboarding='frat-cat-pilot']", title: "Pilot / Crew Factors", description: "Select any pilot or crew risk factors that apply.", advanceOn: "continue" },
      { id: "frat_aircraft_cat", target: "[data-onboarding='frat-cat-aircraft']", title: "Aircraft Factors", description: "Select any aircraft-related risk factors.", advanceOn: "continue" },
      { id: "frat_env", target: "[data-onboarding='frat-cat-environment']", title: "Environment Factors", description: "Select any environmental risk factors for this flight.", advanceOn: "continue" },
      { id: "frat_ops", target: "[data-onboarding='frat-cat-operational']", title: "Operational Factors", description: "Select any operational risk factors.", advanceOn: "continue" },
      { id: "frat_submit", target: "[data-onboarding='frat-score-panel']", title: "Review & Submit", description: "Review your risk score and submit the FRAT. High and critical risk FRATs can be configured by admin to require authorization before dispatch.", advanceOn: "continue" },
      { id: "congrats", target: null, title: "FRAT Submitted!", description: "You've completed your first risk assessment. FRATs are the foundation of proactive safety management.", advanceOn: "dismiss" },
    ],
  },
  flights: {
    id: "flights",
    title: "Flight Following Walkthrough",
    description: "See how to track flights and manage arrivals in your operations center",
    tab: "flights",
    steps: [
      { id: "ff_map", target: "[data-onboarding='ff-map']", title: "Live Flight Map", description: "This map shows all active flights. Aircraft positions update in real-time when ADS-B tracking is enabled.", advanceOn: "continue" },
      { id: "ff_card", target: "[data-onboarding='ff-flight-card']", title: "Flight Card", description: "Each flight shows its route, pilot, risk score, and progress. Click the card to expand it.", advanceOn: "click" },
      { id: "ff_detail", target: "[data-onboarding='ff-adsb-detail']", title: "Flight Details", description: "The expanded view shows live ADS-B tracking data, Mark Arrived to log landings, and all flight details at a glance.", advanceOn: "continue" },
      { id: "congrats", target: null, title: "Flight Following Complete!", description: "You've learned how to track flights and manage arrivals. Your operations center is ready.", advanceOn: "dismiss" },
    ],
  },
  safety_report: {
    id: "safety_report",
    title: "Submit Your First Safety Report",
    description: "Walk through the safety reporting process to learn how your team captures hazards and incidents",
    tab: "reports",
    steps: [
      { id: "sr_new_btn", target: "[data-onboarding='sr-new-btn']", title: "New Report", description: "This is where your team submits safety reports — hazards, incidents, near misses, and concerns. Click + New Report to get started.", advanceOn: "click" },
      { id: "sr_type", target: "[data-onboarding='sr-type']", title: "Report Type", description: "Choose the type of report. Hazards identify potential dangers, incidents document events that occurred, near misses capture close calls, and concerns flag general safety issues.", advanceOn: "continue" },
      { id: "sr_title", target: "[data-onboarding='sr-title']", title: "Title", description: "Give the report a brief, descriptive title. Be specific — good titles help safety managers triage quickly.", advanceOn: "continue" },
      { id: "sr_description", target: "[data-onboarding='sr-description']", title: "Description", description: "Describe what happened, the conditions, and the outcome or potential outcome. Detail matters — this is the foundation of every investigation.", advanceOn: "continue" },
      { id: "sr_details", target: "[data-onboarding='sr-details']", title: "Additional Details", description: "Categorize the event by date, location, category, severity, flight phase, and aircraft. These fields power analytics and trend detection.", advanceOn: "continue" },
      { id: "sr_submit_btn", target: "[data-onboarding='sr-submit-btn']", title: "Submit Report", description: "Review your report and click Submit. Reports go to your safety manager for review and investigation.", advanceOn: "click" },
      { id: "congrats", target: null, title: "Report Submitted!", description: "You've filed your first safety report. Consistent reporting builds a proactive safety culture and satisfies SMS requirements.", advanceOn: "dismiss" },
    ],
  },
  policy_manuals: {
    id: "policy_manuals",
    title: "Set Up Policies & Manuals",
    description: "Configure SMS manual templates and learn how policy acknowledgment works",
    tab: "policy",
    steps: [
      {
        id: "pm_manuals_tab",
        target: "[data-onboarding='policy-manuals-tab']",
        title: "SMS Manual Templates",
        description: "Click SMS Manual Templates to access your pre-built FAA Part 5 manuals.",
        advanceOn: "click",
      },
      {
        id: "pm_init",
        target: "[data-onboarding='sms-init-btn']",
        title: "Set Up Your Manuals",
        description: "Click to generate 7 SMS manual templates covering all Part 5 requirements. These are pre-filled with FAA guidance — you'll customize them with your organization's details.",
        advanceOn: "click",
      },
      {
        id: "pm_variables",
        target: "[data-onboarding='sms-variables']",
        title: "Template Variables",
        description: "Fill in your organization's details here — company name, key personnel, locations, and aircraft. These variables auto-populate across all your manuals.",
        advanceOn: "continue",
      },
      {
        id: "pm_templates",
        target: "[data-onboarding='sms-manual-list']",
        title: "Manual Templates",
        description: "Your 7 SMS manuals cover Safety Policy, Risk Management, Safety Assurance, Safety Promotion, Emergency Response, Hazard Reporting, and more. Click any manual to edit its content and track your progress.",
        advanceOn: "continue",
      },
      {
        id: "pm_policy_tab",
        target: "[data-onboarding='policy-library-tab']",
        title: "Policy Library",
        description: "Click Policy Library to see your published documents and track employee acknowledgment.",
        advanceOn: "click",
      },
      {
        id: "pm_add_doc",
        target: "[data-onboarding='policy-add-doc']",
        title: "Upload Custom Documents",
        description: "Use + Add Document to upload your own policies, SOPs, or manuals. You can attach PDFs or write content directly. Published SMS manuals also appear here automatically.",
        advanceOn: "continue",
      },
      {
        id: "pm_acknowledge",
        target: "[data-onboarding='policy-ack-stats']",
        title: "Employee Acknowledgment",
        description: "When documents are published, employees see an Acknowledge button on each policy. This card tracks acknowledgment rates — essential for FAA compliance and audit readiness.",
        advanceOn: "continue",
      },
      {
        id: "congrats",
        target: null,
        title: "Policies & Manuals Complete!",
        description: "Your SMS documentation is ready. Edit your manuals, fill in template variables, and publish policies for your team to acknowledge.",
        advanceOn: "dismiss",
      },
    ],
  },
  training: {
    id: "training",
    title: "Set Up Training & Compliance",
    description: "Initialize your Part 5 training program and learn how to create courses, track records, and monitor compliance",
    tab: "cbt",
    steps: [
      {
        id: "tr_init",
        target: "[data-onboarding='cbt-init-btn']",
        title: "Initialize Part 5 Training",
        description: "Click to generate a complete Part 5 training program — 5 requirements and 5 courses with 18 lessons covering Safety Policy, Risk Management, Safety Assurance, Emergency Response, and Safety Promotion. These are the exact training areas required under §5.91 for Part 5 compliance.",
        advanceOn: "click",
      },
      {
        id: "tr_course_stats",
        target: "[data-onboarding='cbt-course-stats']",
        title: "Your Training Dashboard",
        description: "Track your course catalog at a glance — total courses available, how many you've completed, and what's in progress. Every team member sees their own progress here.",
        advanceOn: "continue",
      },
      {
        id: "tr_course_list",
        target: "[data-onboarding='cbt-course-list']",
        title: "Training Courses",
        description: "Your Part 5 courses are ready. Each course has lessons with text content, callouts, and quiz questions. Employees complete lessons, pass quizzes, and earn certificates. Click any course to view its lessons and start learning.",
        advanceOn: "continue",
      },
      {
        id: "tr_new_course",
        target: "[data-onboarding='cbt-new-course-btn']",
        title: "Create Your Own Courses",
        description: "Use + New Course to build custom training. Add a title, description, category, set which roles are required to complete it, then add lessons with text content, callouts, and quiz questions. Publish when ready — enrolled users will see it immediately.",
        advanceOn: "continue",
      },
      {
        id: "tr_records_tab",
        target: "[data-onboarding='cbt-records-tab']",
        title: "Training Records",
        description: "Click Training Records to view and log all training — both online courses and external training like classroom sessions, check rides, or recurrent training events.",
        advanceOn: "click",
      },
      {
        id: "tr_records_stats",
        target: "[data-onboarding='cbt-records-stats']",
        title: "Expiry Tracking",
        description: "Training records are tracked as Current (green), Expiring Soon (yellow), or Expired (red). The system automatically checks for expiring training daily and sends email notifications to employees and their managers — so no one misses an annual recurrent deadline.",
        advanceOn: "continue",
      },
      {
        id: "tr_log_training",
        target: "[data-onboarding='cbt-log-training-btn']",
        title: "Log External Training",
        description: "Use + Log Training to record training completed outside the platform — classroom sessions, simulator time, check rides, vendor courses, or anything else. Link it to a requirement, set an expiry date, and it feeds into the compliance matrix.",
        advanceOn: "continue",
      },
      {
        id: "tr_compliance_tab",
        target: "[data-onboarding='cbt-compliance-tab']",
        title: "Compliance Matrix",
        description: "Click Compliance to see who's current on required training and who's behind. This is the view you'll use to prepare for FAA audits and ensure every team member meets §5.91 competency requirements.",
        advanceOn: "click",
      },
      {
        id: "tr_compliance_summary",
        target: "[data-onboarding='cbt-compliance-summary']",
        title: "Team Compliance Status",
        description: "This summary shows how many users are fully compliant across all training requirements. Green dots mean current, yellow means expiring within 30 days, red means expired, and gray means not yet completed.",
        advanceOn: "continue",
      },
      {
        id: "tr_compliance_matrix",
        target: "[data-onboarding='cbt-compliance-matrix']",
        title: "Per-User Compliance Grid",
        description: "The matrix shows every user against every training requirement. At a glance, you can see exactly who needs what training — essential for §5.97(c) training record compliance and audit readiness.",
        advanceOn: "continue",
      },
      {
        id: "congrats",
        target: null,
        title: "Training Program Ready!",
        description: "Your Part 5 training program is set up. Employees can take courses online, and you can track compliance across the entire team. The system will automatically notify users when annual training is coming due — no manual follow-up needed.",
        advanceOn: "dismiss",
      },
    ],
  },
  compliance: {
    id: "compliance",
    title: "Your Path to 100% Compliance",
    description: "See exactly what you need to do to be fully FAA Part 5 compliant and ready to file your Declaration of Compliance",
    tab: "audits",
    steps: [
      {
        id: "comp_overview",
        target: "[data-onboarding='compliance-part5-tab']",
        title: "Part 5 Compliance Checklist",
        description: "This is your live compliance checklist — it tracks all 51 FAA Part 5 requirements and shows exactly what you've completed and what's left. Everything here updates automatically as you use the platform.",
        advanceOn: "continue",
      },
      {
        id: "comp_stats",
        target: "[data-onboarding='compliance-stats']",
        title: "Compliance at a Glance",
        description: "These cards show your total requirements, how many are compliant, and how many need attention. Your goal is to get all 51 to green. Let's walk through exactly how to get there.",
        advanceOn: "continue",
      },
      {
        id: "comp_progress",
        target: "[data-onboarding='compliance-progress']",
        title: "Part 5 Readiness Score",
        description: "This bar shows your overall compliance percentage. When it hits 100%, you're ready to generate your Declaration of Compliance and file it with the FAA.",
        advanceOn: "continue",
      },
      {
        id: "comp_manuals",
        target: "[data-onboarding='compliance-manuals']",
        title: "1. Complete Your SMS Manuals",
        description: "This is the biggest single step — completing your 7 SMS manual templates covers 40 of the 51 requirements. Each manual maps to specific Part 5 sections. Go to Documents > SMS Manual Templates, fill in your template variables, and complete each manual section-by-section.",
        advanceOn: "continue",
      },
      {
        id: "comp_subparts",
        target: "[data-onboarding='compliance-subparts']",
        title: "Requirements by Subpart",
        description: "All 51 requirements are organized into 6 subparts: General, Safety Policy, Safety Risk Management, Safety Assurance, Safety Promotion, and Documentation. Expand any subpart to see individual requirements and what satisfies each one.",
        advanceOn: "continue",
      },
      {
        id: "comp_frats",
        target: "[data-onboarding='compliance-filters']",
        title: "2. Submit FRATs",
        description: "Submitting Flight Risk Assessments satisfies Safety Risk Management requirements (Subpart C) — risk analysis, risk assessment, hazard identification, and risk controls. Even one FRAT demonstrates an active SRM process.",
        advanceOn: "continue",
      },
      {
        id: "comp_reports",
        target: "[data-onboarding='compliance-filters']",
        title: "3. File Safety Reports",
        description: "Safety reports satisfy Safety Assurance requirements (Subpart D) — employee reporting, hazard identification through data, continuous information gathering, and recordkeeping. Your team should report hazards, incidents, and near misses.",
        advanceOn: "continue",
      },
      {
        id: "comp_hazards_actions",
        target: "[data-onboarding='compliance-filters']",
        title: "4. Track Hazards & Corrective Actions",
        description: "Log hazards in the Hazard Register and create corrective actions to track risk controls. This satisfies requirements for hazard identification, risk control development, corrective action monitoring, and continuous improvement.",
        advanceOn: "continue",
      },
      {
        id: "comp_roles",
        target: "[data-onboarding='compliance-filters']",
        title: "5. Assign Key Roles",
        description: "In Admin > Team, assign an Accountable Executive and Safety Manager. These roles satisfy §5.23–5.25 requirements for safety accountability, authority documentation, and management personnel designation.",
        advanceOn: "continue",
      },
      {
        id: "comp_training",
        target: "[data-onboarding='compliance-filters']",
        title: "6. Record Training",
        description: "Log SMS training for your personnel in the Training module. This satisfies §5.91 (competencies and training) and §5.97(c) (training records). All employees with SMS duties need documented training.",
        advanceOn: "continue",
      },
      {
        id: "comp_policies",
        target: "[data-onboarding='compliance-filters']",
        title: "7. Publish & Acknowledge Policies",
        description: "Upload policies to the Policy Library and have employees acknowledge them. This satisfies §5.21(c) (policy communication), §5.93(a) (SMS awareness), and §5.93(d) (procedure change communication). Acknowledged policies are your compliance proof.",
        advanceOn: "continue",
      },
      {
        id: "comp_doc",
        target: "[data-onboarding='compliance-doc-btn']",
        title: "8. File Your Declaration of Compliance",
        description: "When you hit 100%, this button generates your formal Declaration of Compliance — a letter to the FAA per AC 120-92D and Notice 8900.700. It auto-populates with your compliance data, evidence, and milestones. This is the final step to being officially SMS compliant.",
        advanceOn: "continue",
      },
      {
        id: "congrats",
        target: null,
        title: "You Know the Path to 100%!",
        description: "Complete your SMS manuals, submit FRATs, file safety reports, track hazards, assign roles, record training, and publish policies. When you're at 100%, generate your Declaration of Compliance. Every action you take in PreflightSMS automatically moves you closer to full FAA Part 5 compliance.",
        advanceOn: "dismiss",
      },
    ],
  },
};

export const FLOW_ORDER = ["fleet", "frat", "flights", "safety_report", "policy_manuals", "training", "compliance"];
