export const ONBOARDING_FLOWS = {
  fleet: {
    id: "fleet",
    title: "Add Your First Aircraft",
    description: "Register an aircraft to enable flight tracking and FRAT submissions",
    tab: "admin",
    adminTab: "fleet",
    steps: [
      {
        id: "enter_type",
        target: "[data-onboarding='fleet-type-input']",
        title: "Aircraft Type",
        description: "Enter your aircraft type — for example, C172 or R44.",
        advanceOn: "continue",
      },
      {
        id: "enter_reg",
        target: "[data-onboarding='fleet-reg-input']",
        title: "Tail Number",
        description: "Enter the registration / tail number. We'll auto-add the N prefix.",
        advanceOn: "continue",
      },
      {
        id: "complete_form",
        target: "[data-onboarding='fleet-form']",
        title: "Complete the Details",
        description: "Fill in any remaining fields, then click Add Aircraft to save.",
        advanceOn: "save",
      },
      {
        id: "congrats",
        target: null,
        title: "Aircraft Added!",
        description: "Your fleet is started. You're ready to track flights and submit risk assessments.",
        advanceOn: "dismiss",
      },
    ],
  },
  frat: {
    id: "frat",
    title: "Submit Your First FRAT",
    description: "Walk through a Flight Risk Assessment to learn how risk scoring works",
    tab: "submit",
    steps: [
      { id: "frat_pilot", target: "[data-onboarding='frat-pilot']", title: "Pilot in Command", description: "Enter the pilot's name for this flight.", advanceOn: "continue" },
      { id: "frat_aircraft", target: "[data-onboarding='frat-aircraft']", title: "Aircraft", description: "Select the aircraft type from your fleet.", advanceOn: "continue" },
      { id: "frat_departure", target: "[data-onboarding='frat-departure']", title: "Departure Airport", description: "Enter the ICAO code for your departure airport (e.g. KSFF).", advanceOn: "continue" },
      { id: "frat_destination", target: "[data-onboarding='frat-destination']", title: "Destination Airport", description: "Enter the ICAO code for your destination (e.g. KBOI).", advanceOn: "continue" },
      { id: "frat_remaining", target: "[data-onboarding='frat-flight-info']", title: "Complete Flight Details", description: "Fill in the remaining fields — altitude, date, times, fuel, crew, and passengers.", advanceOn: "continue" },
      { id: "frat_photos", target: "[data-onboarding='frat-photos']", title: "Attachments", description: "Attach photos of HAZMAT PIC notifications or other documents. This step is optional — click Continue to proceed.", advanceOn: "continue" },
      { id: "frat_wx_brief", target: "[data-onboarding='frat-weather-briefing']", title: "Weather Briefing", description: "Review the weather briefing for your departure and destination airports. METARs, TAFs, and flight rules are displayed automatically.", advanceOn: "continue" },
      { id: "frat_ai", target: "[data-onboarding='frat-ai-panel']", title: "AI Risk Suggestions", description: "Try AI-powered risk analysis. AI suggests risk categories based on historical FRATs, your planned flight, current weather, and terrain data.", advanceOn: "continue" },
      { id: "frat_wx", target: "[data-onboarding='frat-cat-weather']", title: "Weather Factors", description: "Review and select any weather hazards that apply to this flight.", advanceOn: "continue" },
      { id: "frat_pilot_cat", target: "[data-onboarding='frat-cat-pilot']", title: "Pilot / Crew Factors", description: "Select any pilot or crew risk factors that apply.", advanceOn: "continue" },
      { id: "frat_aircraft_cat", target: "[data-onboarding='frat-cat-aircraft']", title: "Aircraft Factors", description: "Select any aircraft-related risk factors.", advanceOn: "continue" },
      { id: "frat_env", target: "[data-onboarding='frat-cat-environment']", title: "Environment Factors", description: "Select any environmental risk factors for this flight.", advanceOn: "continue" },
      { id: "frat_ops", target: "[data-onboarding='frat-cat-operational']", title: "Operational Factors", description: "Select any operational risk factors.", advanceOn: "continue" },
      { id: "frat_submit", target: "[data-onboarding='frat-score-panel']", title: "Review & Submit", description: "Review your risk score and submit the FRAT. High and critical risk FRATs can be configured by admin to require authorization before dispatch.", advanceOn: "continue" },
      { id: "congrats", target: null, title: "FRAT Submitted!", description: "You've completed your first risk assessment. FRATs are the foundation of proactive safety management.", advanceOn: "dismiss" },
    ],
  },
  flights: {
    id: "flights",
    title: "Flight Following Walkthrough",
    description: "See how to track flights and manage arrivals in your operations center",
    tab: "flights",
    steps: [
      { id: "ff_map", target: "[data-onboarding='ff-map']", title: "Live Flight Map", description: "This map shows all active flights. Aircraft positions update in real-time when ADS-B tracking is enabled.", advanceOn: "continue" },
      { id: "ff_card", target: "[data-onboarding='ff-flight-card']", title: "Flight Card", description: "Each flight shows its route, pilot, risk score, and progress. Click the card to expand it.", advanceOn: "click" },
      { id: "ff_detail", target: "[data-onboarding='ff-adsb-detail']", title: "Flight Details", description: "The expanded view shows live ADS-B tracking data, Mark Arrived to log landings, and all flight details at a glance.", advanceOn: "continue" },
      { id: "congrats", target: null, title: "Flight Following Complete!", description: "You've learned how to track flights and manage arrivals. Your operations center is ready.", advanceOn: "dismiss" },
    ],
  },
  safety_report: {
    id: "safety_report",
    title: "Submit Your First Safety Report",
    description: "Walk through the safety reporting process to learn how your team captures hazards and incidents",
    tab: "reports",
    steps: [
      { id: "sr_new_btn", target: "[data-onboarding='sr-new-btn']", title: "New Report", description: "This is where your team submits safety reports — hazards, incidents, near misses, and concerns. Click + New Report to get started.", advanceOn: "click" },
      { id: "sr_type", target: "[data-onboarding='sr-type']", title: "Report Type", description: "Choose the type of report. Hazards identify potential dangers, incidents document events that occurred, near misses capture close calls, and concerns flag general safety issues.", advanceOn: "continue" },
      { id: "sr_title", target: "[data-onboarding='sr-title']", title: "Title", description: "Give the report a brief, descriptive title. Be specific — good titles help safety managers triage quickly.", advanceOn: "continue" },
      { id: "sr_description", target: "[data-onboarding='sr-description']", title: "Description", description: "Describe what happened, the conditions, and the outcome or potential outcome. Detail matters — this is the foundation of every investigation.", advanceOn: "continue" },
      { id: "sr_details", target: "[data-onboarding='sr-details']", title: "Additional Details", description: "Categorize the event by date, location, category, severity, flight phase, and aircraft. These fields power analytics and trend detection.", advanceOn: "continue" },
      { id: "sr_submit_btn", target: "[data-onboarding='sr-submit-btn']", title: "Submit Report", description: "Review your report and click Submit. Reports go to your safety manager for review and investigation.", advanceOn: "click" },
      { id: "congrats", target: null, title: "Report Submitted!", description: "You've filed your first safety report. Consistent reporting builds a proactive safety culture and satisfies SMS requirements.", advanceOn: "dismiss" },
    ],
  },
  policy_manuals: {
    id: "policy_manuals",
    title: "Set Up Policies & Manuals",
    description: "Configure SMS manual templates and learn how policy acknowledgment works",
    tab: "policy",
    steps: [
      {
        id: "pm_manuals_tab",
        target: "[data-onboarding='policy-manuals-tab']",
        title: "SMS Manual Templates",
        description: "Click SMS Manual Templates to access your pre-built FAA Part 5 manuals.",
        advanceOn: "click",
      },
      {
        id: "pm_init",
        target: "[data-onboarding='sms-init-btn']",
        title: "Set Up Your Manuals",
        description: "Click to generate 7 SMS manual templates covering all Part 5 requirements. These are pre-filled with FAA guidance — you'll customize them with your organization's details.",
        advanceOn: "click",
      },
      {
        id: "pm_variables",
        target: "[data-onboarding='sms-variables']",
        title: "Template Variables",
        description: "Fill in your organization's details here — company name, key personnel, locations, and aircraft. These variables auto-populate across all your manuals.",
        advanceOn: "continue",
      },
      {
        id: "pm_templates",
        target: "[data-onboarding='sms-manual-list']",
        title: "Manual Templates",
        description: "Your 7 SMS manuals cover Safety Policy, Risk Management, Safety Assurance, Safety Promotion, Emergency Response, Hazard Reporting, and more. Click any manual to edit its content and track your progress.",
        advanceOn: "continue",
      },
      {
        id: "pm_policy_tab",
        target: "[data-onboarding='policy-library-tab']",
        title: "Policy Library",
        description: "Click Policy Library to see your published documents and track employee acknowledgment.",
        advanceOn: "click",
      },
      {
        id: "pm_add_doc",
        target: "[data-onboarding='policy-add-doc']",
        title: "Upload Custom Documents",
        description: "Use + Add Document to upload your own policies, SOPs, or manuals. You can attach PDFs or write content directly. Published SMS manuals also appear here automatically.",
        advanceOn: "continue",
      },
      {
        id: "pm_acknowledge",
        target: "[data-onboarding='policy-ack-stats']",
        title: "Employee Acknowledgment",
        description: "When documents are published, employees see an Acknowledge button on each policy. This card tracks acknowledgment rates — essential for FAA compliance and audit readiness.",
        advanceOn: "continue",
      },
      {
        id: "congrats",
        target: null,
        title: "Policies & Manuals Complete!",
        description: "Your SMS documentation is ready. Edit your manuals, fill in template variables, and publish policies for your team to acknowledge.",
        advanceOn: "dismiss",
      },
    ],
  },
};

export const FLOW_ORDER = ["fleet", "frat", "flights", "safety_report", "policy_manuals"];
