// Subscription tier definitions and feature gating

export const FREE_TIER_LIMITS = {
  maxAircraft: 1,
  maxUsers: 1,
  maxOpenActions: 5,
  maxPolicies: 3,
  maxErpPlans: 1,
  investigationsViewOnly: true,
  smsManualReadOnly: true,
  dashboardBasicOnly: true,
  pdfWatermark: true,
};

export const TIERS = {
  free: {
    name: "Free",
    price: 0,
    maxAircraft: 1,
    features: {
      fleet: true,
      frat: true,
      flight_following: false,
      safety_reporting: true,
      hazard_register: "view_only",
      corrective_actions: true,
      policy_library: true,
      training_records: false,
      dashboard_basic: true,
      dashboard_analytics: false,
      safety_trend_alerts: false,
      scheduled_reports: false,
      audit_program: false,
      faa_audit_log: false,
      custom_frat_template: false,
      cbt_modules: false,
      role_permissions: false,
      approval_workflow: false,
      document_library: false,
      sms_manuals: "read_only",
      api_access: false,
      multi_base: false,
      custom_integrations: false,
      foreflight_integration: false,
      schedaero_integration: false,
      internal_evaluation: false,
      management_of_change: false,
      safety_culture_survey: false,
      fatigue_assessment: false,
      asap_program: false,
      international_compliance: false,
      insurance_export: false,
      adsb_tracking: false,
      priority_support: false,
    },
  },
  starter: {
    name: "Starter",
    price: 149,
    maxAircraft: 5,
    features: {
      fleet: true,
      frat: true,
      flight_following: true,
      safety_reporting: true,
      hazard_register: true,
      corrective_actions: true,
      policy_library: true,
      training_records: true,
      dashboard_basic: true,
      dashboard_analytics: false,
      safety_trend_alerts: false,
      scheduled_reports: false,
      audit_program: false,
      faa_audit_log: false,
      custom_frat_template: false,
      cbt_modules: true,
      role_permissions: false,
      approval_workflow: false,
      document_library: false,
      sms_manuals: true,
      api_access: false,
      multi_base: false,
      custom_integrations: false,
      foreflight_integration: false,
      schedaero_integration: false,
      internal_evaluation: false,
      management_of_change: false,
      safety_culture_survey: false,
      fatigue_assessment: false,
      asap_program: false,
      international_compliance: false,
      insurance_export: false,
      adsb_tracking: false,
      priority_support: false,
    },
  },
  professional: {
    name: "Professional",
    price: 349,
    maxAircraft: 15,
    features: {
      fleet: true,
      frat: true,
      flight_following: true,
      safety_reporting: true,
      hazard_register: true,
      corrective_actions: true,
      policy_library: true,
      training_records: true,
      dashboard_basic: true,
      dashboard_analytics: true,
      safety_trend_alerts: true,
      scheduled_reports: true,
      audit_program: true,
      faa_audit_log: true,
      custom_frat_template: true,
      cbt_modules: true,
      role_permissions: true,
      approval_workflow: true,
      document_library: true,
      sms_manuals: true,
      api_access: "read_only",
      multi_base: false,
      custom_integrations: false,
      foreflight_integration: true,
      schedaero_integration: true,
      internal_evaluation: true,
      management_of_change: true,
      safety_culture_survey: true,
      fatigue_assessment: true,
      asap_program: false,
      international_compliance: false,
      insurance_export: true,
      adsb_tracking: true,
      priority_support: true,
    },
  },
  enterprise: {
    name: "Enterprise",
    price: null, // Custom
    maxAircraft: 999,
    features: {
      fleet: true,
      frat: true,
      flight_following: true,
      safety_reporting: true,
      hazard_register: true,
      corrective_actions: true,
      policy_library: true,
      training_records: true,
      dashboard_basic: true,
      dashboard_analytics: true,
      safety_trend_alerts: true,
      scheduled_reports: true,
      audit_program: true,
      faa_audit_log: true,
      custom_frat_template: true,
      cbt_modules: true,
      role_permissions: true,
      approval_workflow: true,
      document_library: true,
      sms_manuals: true,
      api_access: true,
      multi_base: true,
      custom_integrations: true,
      foreflight_integration: true,
      schedaero_integration: true,
      internal_evaluation: true,
      management_of_change: true,
      safety_culture_survey: true,
      fatigue_assessment: true,
      asap_program: true,
      international_compliance: true,
      insurance_export: true,
      adsb_tracking: true,
      priority_support: true,
    },
  },
};

// Feature display names for UI
export const FEATURE_LABELS = {
  fleet: "Fleet Management",
  frat: "Flight Risk Assessment (FRAT)",
  flight_following: "Flight Following",
  safety_reporting: "Safety Reporting",
  hazard_register: "Investigation Register",
  corrective_actions: "Corrective Actions",
  policy_library: "Policy Library",
  training_records: "Training Records",
  dashboard_basic: "Dashboard (Basic Stats)",
  dashboard_analytics: "Dashboard Analytics (Trends & Charts)",
  safety_trend_alerts: "Safety Trend Alerts",
  scheduled_reports: "Scheduled PDF Reports",
  audit_program: "Audit & Compliance Program",
  faa_audit_log: "FAA Part 5 Audit Log",
  custom_frat_template: "Custom FRAT Templates",
  cbt_modules: "Training & CBT Modules",
  role_permissions: "Role-Based Permissions",
  approval_workflow: "FRAT Approval Workflow",
  document_library: "Document Library & Version Control",
  sms_manuals: "SMS Manual Templates",
  api_access: "API Access",
  multi_base: "Multi-Base Support",
  custom_integrations: "Custom Integrations",
  foreflight_integration: "ForeFlight Integration",
  schedaero_integration: "Schedaero Integration",
  internal_evaluation: "Internal Evaluation Program (IEP)",
  management_of_change: "Management of Change",
  safety_culture_survey: "Safety Culture Survey",
  fatigue_assessment: "Fatigue Risk Assessment",
  asap_program: "Aviation Safety Action Program (ASAP)",
  international_compliance: "International Compliance (ICAO, IS-BAO, EASA)",
  insurance_export: "Insurance Data Export & Safety Scorecard",
  adsb_tracking: "Live ADS-B Flight Tracking",
  priority_support: "Priority Support",
};

// Check if a specific feature is enabled for an org
export function hasFeature(org, featureKey) {
  if (!org) return false;
  // Check feature_flags on the org object (overrides tier defaults)
  if (org.feature_flags && typeof org.feature_flags === "object") {
    if (featureKey in org.feature_flags) return org.feature_flags[featureKey];
  }
  // Fall back to tier defaults
  const tier = TIERS[org.tier || "starter"];
  return tier?.features?.[featureKey] ?? false;
}

// Check if org is on free tier
export function isFreeTier(org) {
  if (!org) return false;
  return (org.tier || "starter") === "free";
}

// Get the default feature set for a tier
export function getTierFeatures(tierName) {
  return TIERS[tierName]?.features || TIERS.starter.features;
}

// Map nav items to required features
export const NAV_FEATURE_MAP = {
  fleet: "fleet",
  submit: "frat",
  flights: "flight_following",
  reports: "safety_reporting",
  hazards: "hazard_register",
  actions: "corrective_actions",
  policy: "policy_library",
  cbt: "cbt_modules",
  audits: "audit_program",
  moc: "management_of_change",
  manuals: "sms_manuals",
  dashboard: "dashboard_basic",
  asap: "asap_program",
  admin: null, // always available
};
